- lib/modem.js
- test/modem_test.js
The `docker` command and a number of other tools support a `DOCKER_HOST` environment variable in the format `unix:///path/to/docker.sock`. Now `docker-modem`-based apps can too.
I also took the liberty of adding a test for the existing port 2376 TLS behavior.
> Add support for DOCKER_HOST=unix://

- lib/modem.js
Error responses were only included if they were JSON.
This PR adds some code to consume streamed responses, too.
> Get error cause from streamed error response bodies

- lib/modem.js
Working on some dockerode functionality which requires me to send an Authorization header.
> Allow passing headers when dialling

- lib/modem.js
I am working currently on a Docker remote API proxy, I already get the AuthConfig object has a base64-encoded string from the request header.
This  patch allow to use a already base64-encoded AuthConfig string instead of a plain AuthConfig object.
> add key to override authconfig object encoding

- lib/modem.js
This allows for the user to define a custom `checkServerIdentity` function to override the default certificate hostname verification function (`tls. checkServerIdentity`)
> added checkServerIdentity override

- package.json
- test/modem_test.js
There are a lot of problems with JSONStream vs. jsonstream due to
case-folding and case-insensitive filesystems and how npm's cache
works. The best way forward is for everyone to standardize on
jsonstream, which is the canonical name for the module formerly called
JSONStream.
Also fixes a failing test that wasn't accounting for DOCKER_TLS_VERIFY being set in the environment, which is the case when using boot2docker.
> Update JSONStream@0.10 to jsonstream@1

- lib/modem.js
- test/modem_test.js
This better matches the behaviour of docker itself, so it avoids the
problem of "hey, docker works, why doesn't dockerode?" and some hair
pulling.
@apocas hopefully this PR works out better than #43 did ;-)
/cc @altsang @sam-github
> Make 'tcp://' optional when reading DOCKER_HOST

- lib/modem.js
- package.json
For custom CA setups where there are intermediate certificate chains, docker modem needs to support splitting the CA certificate into an array for node.
> allow for ca certs that contain a chain

- lib/modem.js
Implements the client side of HTTP connection hijacking described in
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#3-2-hijacking
This would allow a raw TCP socket to be passed back instead of using a
custom HTTP Duplex implementation for:
- POST /containers/(id)/attach
- POST /exec/(id)/start
It doesn't seem to be completely documented, but it appears that any
endpoint that responds with a `{{ STREAM }}` (muxed stdout/stderr) can
be upgraded to a plain TCP connection.
This implementation works, but isn't complete in that it doesn't
include tests and may not handle all cases. I didn't want to put in
all that effort until there was a discussion about it.
@apocas what do you think?
> proposal: use upgraded connections for streams

- lib/modem.js
- test/modem_test.js
this PR provides the `Modem.buildQuerystring` method which will auto-encode map values as JSON strings (which the docker API expects). Previously map values were _silently_ truncated by querystring.stringify. This approach allows more accessible/friendly management of options, for instance when passing labels as seen in this test ::
```
it("should query containers filtering by map of valued labels", function(done){
docker.listContainers({
"limit": 3,
"filters": {
"label": ["dockerode-test-label","dockerode-test-value-label=assigned"]
}
}, function(err, data){
expect(data.length).to.equal(1);
done();
});
});
```
I choose to use a method for this, as it's monkey-patchable.  A PR will be submitted to the dockerode project testing and documenting this functionality.
> auto encode querystring option maps as JSON

- lib/modem.js
Unexpeced errors were not handled correctly ('undefined') and the cause coming from the json was serialized as `[object Object]` instead of the correct message.
Original error message (start returning 400):
`HTTP code is 400 which indicates error: undefined - [object Object]`
Now:
`(HTTP code 400) unexpected - starting container with HostConfig was deprecated since v1.10 and removed in v1.12`
> Unexpeced errors were not handled correctly

- package.json
Packages should include an SPDX-compatible license name in their
package.json. Otherwise a warning will be printed when the module is
installed. This commit adds that field.
> Add SPDX license field

- package.json
I was unable to install dockerode using `ied` because follow-redirects 0.0.3 has a bad package.json file* that apparently npm deals with but some other installers can't. This pull request updates the dependency to a newer version of follow-redirects that doesn't have this issue.
I've been using a patched version of docker-modem and dockerode and haven't had any trouble.
* specifically, it lists "underscore": "" in its dependencies, with that empty string for the version.
> Newer version of follow-redirects

- lib/modem.js
Remove authconfig details from the address URL. 
These show up in the logs (docker logs) and are only used in the `X-Registry-Auth` part of the header.
> Cleaned up logic for authconfig

- lib/modem.js
When using a stream with docker modem there is no header 'Content-Length' since there is no known length to it. The right replacement for that is using the header 'Transfer-Encoding: chunked'.
This can cause problem with docker daemon as an example: when building an image and canceling (by exiting process or destroying connection) omitting this header while using a stream cause the daemon to ignore the dropped connection and continue the build.
> Adding a 'Transfer-Encoding' header when using stream

- lib/modem.js
The header `Transfer-Encoding: chunked` prevents docker daemon from closing the opened fds after canceling the log stream.
> Remove the 'Transfer-Encoding' header in requests without body

- lib/modem.js
- test/modem_test.js
As you can see at https://docs.docker.com/engine/api/v1.29/#operation/ImageBuild, the `build` command is the only operation that supports multiple `t=foo&t=bar` parameters instead of everywhere else where it's a JSON array `other=["foo","bar"]`. This minor change allows multiple tags to be specified through the API when building and saves me from having to create a `tmp` tag that I have to retag with the actual tags I want later.
> Fix `t` query parameter for `build` command

- lib/modem.js
Change modem.followProgress() to listen for `data` event instead of `root` since `root` will never get fired.
Current behavior: https://github.com/apocas/dockerode/issues/439#issue-302058751
After the fix
> Fix followProgress() not triggering progress handler

- lib/modem.js
Closes #79 
Blocking node event loop and loading the whole file in memory has a pretty bad impact on apps. Especially for large containers.
This is a very minimal fix that stream the file directly to docker. The support was already there but the way of reading the file was wrong.
Tested to be even in resource-constrained systems.
> Stream data directly from file system instead of loading it in memory

- lib/modem.js
I ran into this problem when trying to get the logs from a container. The string I got back was not parseable. The problem is that converting a Buffer that contains the Docker stream control headers gets mangled in such a way that it cannot be converted back for parsing.
For example, if Docker returns a chunk like this:
```
<Buffer 02 00 00 00 00 00 00 98 5b 54 ... >
```
Converting that to a string and back results in a Buffer that looks like this:
```
<Buffer 02 00 00 00 00 00 00 ef bf bd 5b 54 ... >
```
Notice the two extra bytes, making the header un-parseable. No combination of string encodings changes this, either.
This pull request proposes that instead of concatenating all of the chunks into a string, they are instead concatenated into a larger Buffer, so the end user can …
> Return a buffer instead of a chunked string

- lib/modem.js
- test/modem_test.js
uses default opts if someone does 'new Modem({ })' with empty argument. Also adds two new tests and fixes an existing one to run on windows.
> Interpret empty object as default opts and fix tests on windows

- lib/modem.js
- lib/ssh.js
- package-lock.json
- package.json
Currently, I have so it creates a new ssh connection on every request. Do you think the ssh connection should persist? So you think it should be an option?
```javascript
var Docker = require("dockerode");
var fs = require('fs');
var key = fs.readFileSync('/path/to/ssh-key');
var docker = new Docker({
protocol: 'ssh',
host: 'localhost',
ssh: {
privateKey: key,
username: 'root'
}
});
docker.listImages((e,d) => {
console.log('img', e, d);
});
docker.info((e,d) => {
console.log('con', e, d);
});
```
fixes #99
> Add ssh protocol support.

- lib/modem.js
I have many requests to the docker deamon. Now the number of TCP connections is increasing very fast. For me there are now several thousand connections, which are no longer used, but are not cleaned up by the OS yet. 
That's why I want to use my own agent for the http request. 
With this change I only have a few connections left to the Docker Daemon.
Now I can define the agent as follows:
const docker = new Docker({
"protocol": "http",
"host": "127.0.0.1",
"port": "2375",
"agent": new http.Agent({
"keepAlive": true,
"maxSockets": 10,
"keepAliveMsecs": 10000
})
});
> allow custome http/s agent

- lib/modem.js
Demux now works using `.on('data')` which prevents read from being called while the stream is in `flowing` mode which can cause the internal buffer to already be drained while trying to read. This implementation borrows heavily from https://github.com/Nathan219/docker-stream-cleanser but is reduced to try to match this use-case as much as possible.
https://nodejs.org/api/stream.html#stream_readable_read_size
> This method should only be called in paused mode. In flowing mode, this method is called automatically until the internal buffer is drained.
> Converted demux to work on.('data')

- lib/modem.js
In Windows, `DOCKER_HOST` can contain things like `npipe:////./pipe/docker_engine` or `npipe:////./pipe/docker_wsl`.
Currently it isn't possible to use `DOCKER_HOST` = `npipe:////./pipe/docker_wsl` to use the WSL2 Docker engine; rather, you must pass in `socketPath` to dockerode. If you try using the above for `DOCKER_HOST` you'll get an error.
> Support npipe:// in DOCKER_HOST

- lib/modem.js
Resolves #107 
* Allow SSH `DOCKER_HOST` URLs
* Accept username in `DOCKER_HOST`, i.e. `ssh://user@host`
* Use `SSH_AUTH_SOCK` env var to determine auth agent (Docker CLI also requires `ssh-agent` to be set up)
> Accept username and agent for SSH

- lib/modem.js
SSH password authentication is quite common and with a strong password can be quite secure. Let's support it in `docker-modem` and `dockerode`.
All that's needed to support it is to pass `opts.password` through to the underlying `ssh` library :)
> Support SSH password authentication

- lib/modem.js
Like #117, add a common SSH option supported by [ssh2](https://github.com/mscdex/ssh2#client-methods).
All we need to do is pass it in the constructor.
> Support agent forwarding over SSH

- lib/modem.js
- test/modem_test.js
This allows for an arbitrary `sshOptions` to be passed in `Modem` options and be used when passed to the `ssh` constructor to get an agent from the `ssh2` library.
This is a breaking change as some previous options are no longer supported.
Effectively reverts b565f5595d255e6e8149abe82dfacc2d9cff7c07, d2f92b22cf284d537a57cc255ba11b4c4c5d7b61, and part of 05f4319aa070c74b967b3ad2342e4d2243980cbf.
> Allow arbitrary sshOptions to be passed to ssh2

- lib/modem.js
Node's `readable.pipe()` does not forward errors of input streams to the writable stream. This causes the build request to just hang. `stream.pipeline()` available in Node >= 10.0 would solve this problem, but it seems more reasonable to just call `req.destroy(error)` on input stream errors for backwards compatibility.
> Handle build data input stream errors correctly

- lib/modem.js
This will make it possible to abort Dockerode requests (https://github.com/apocas/dockerode/issues/629). In practice this looks like:
```javascript
const abortController = new AbortController();
modem.dial({
// ...
abortSignal: abortController.signal
});
// Later, abort the ongoing request:
abortController.abort();
// -> The request returns an AbortError (code: ABORT_ERROR)
```
I've tested this in Dockerode already, and there will be PR there coming shortly that uses this.
Using this in practice requires either Node 16, or Node 14+ with your own AbortController implementation that polyfills the standard (probably https://www.npmjs.com/package/node-abort-controller).
In other environments nothing breaks, you just can't abort requests, because the `signal` option is ignored by the HTTP …
> Add support for abortSignal, to abort requests with an AbortController

- lib/modem.js
Previously there was a check if the options field has the key `t` to
avoid mistransforming the tags list. On build `extra_hosts` are passed
as a JSON string and wouldn't be applied.
We resolve this through checking for an array.
Fixes https://github.com/apocas/dockerode/issues/605
> Don't json-encode array option fields

- lib/modem.js
After my previous PR which excludes array fields from being transformed
to JSON this was broken.
Sorry, I should have done a full test of all the options before submitting the last patch :P
> Add exception to json-encode cachefrom option

- lib/modem.js
Most Docker API parameters take JSON values but some array parameters must be passed as multiple querystring parameters. Two known such parameters are `t` and `extrahosts` for the `/build` endpoint. There may be others.
This changes Modem to behave in a similar way: encode values to JSON by default, except the known special cases.
This properly fixes https://github.com/apocas/dockerode/issues/605 and #139 and effectively reverts #133 and #134.
> Correctly exclude a few keys from being JSON encoded

- lib/modem.js
- package.json
Starting from version 1.39, Docker Engine API uses base64url for X-Registry-Auth header encoding. It breakes authentication when password or username contains "~".
https://docs.docker.com/engine/api/v1.41/#section/Authentication
https://datatracker.ietf.org/doc/html/rfc4648#section-5
> add base64url encoding for auth header; patch version upgrade

- lib/modem.js
**Problem:** the native http/https 'request' method only handles aborting (through AbortSignal) during the request lifecycle not the response lifecycle. It means that if the AbortSignal is triggered while we are processing the response data, it will be ignored an we will the result as if nothing was aborted.
**Example:**
Considering this code:
```ts
import https from 'https'
import { addAbortSignal } from 'stream'
const abortController = new AbortController()
const req = https.request('https://www.google.com', { signal: abortController.signal })
req.on('response', (res) => {
console.log('res')
// Fix
// addAbortSignal(abortController.signal, res)
const chunks = []
res.on('data', (chunk: Buffer) => {
console.log('data', chunk.length)
chunks.push(chunk)
// Option 4: request and response …
```
> fix: handles abort signal in response lifecycle

- lib/modem.js
This commit add path prefix for nested HTTP APIs with customized routing. For example I can mount docker's api proxy to `/system/docker/` on my server.
Also:
* Add DOCKER_PATH_PREFIX env variable
* Cleanup dependencies
* Remove redundant self variable
* Reorder dependencies
> Add pathPrefix option

- lib/modem.js
- test/modem_test.js
This fixes #156. On Mac and Linux, if `$HOME/.docker/run/docker.sock` is present, that will be used by default. If not, the previous `/var/run/docker.sock` will be used instead.
This needs to change a few things, because the check for this is async. To make that work, `socketPath` can now be a function that returns a promise, in which case this will be run and awaited during `dial`.
This shouldn't be a breaking change, but it probably is because (just searching around GitHub) there's quite a few projects that look at `modem.socketPath` directly to see which path was detected. Fortunately it looks like you're already on track for a v4 breaking release anyway, so we can sneak this in there too :smile:.
To make that change easier for downstream users, and to simplify the internals too, this …
> Use the per-user Docker socket as the Unix default, if present

- lib/ssh.js
Was running into an issue where I couldn't catch an error if the SSH client timed out. Adding the `.on` catch enabled me to catch it from the parent application. If it needs more changes, please let me know. For now I'm just patching it with `pnpm patch` which I would prefer not to do.
> Update ssh.js to add error handling.

- lib/http_duplex.js
Hello apocas 😄 
i noticed that Sockets get closed to early when youre calling end on the HttpDuplex Object.
This should fix it as intended by https://nodejs.org/api/net.html#socketdestroysoon
To replicate the issue just try this:
```js
const container = docker.getContainer("1234abcd");
container.attach({ stream: true, stdin: true }, function (err, stream) {
stream.write("Hello World!\n");
stream.end();
});
```
Sincerely,
Michell
> Fix Socket closing to early when the buffer has not flushed yet.

- lib/modem.js
As discussed here: https://github.com/apocas/dockerode/issues/751. It looks like this was an unintentional change made during the "revert" in https://github.com/apocas/docker-modem/commit/8e054177ded397b6166159fd723b0e45445d3ae7.
> Return raw buffer instead of string

- lib/modem.js
> fix: check for error field when looking for cause of error

- lib/ssh.js
This fixes handling ssh connection errors by using error callback instead of throwing an exception when appropriate.
This resolves issue apocas/dockerode#764 and replaced pull request #163
> Fix handling of SSH network errors

- lib/modem.js
- package-lock.json
- package.json
Currently, if `timeout` option is provided, one more event listener is added to the underlying socket _on each request_. This causes the number of `timeout` event listeners for each socket to grow over time until the socket is destroyed. In my tests, the number of event listeners for single socket can exceed 400.
Moreover, it closures Request object within timeout handler preventing it from being garbage collected far beyond its lifecycle.
This PR changes timeout implementation, by adding `timeout` event listener directly to the Request object instead of the Socket. Considering that `request.setTimeout` implicitly calls an appropriate `socket.setTimeout()` ([docs](https://nodejs.org/docs/latest-v20.x/api/net.html#socketsettimeouttimeout-callback)); and `timeout` event is propagated from …
> fix: fix memory leak if `timeout` is set

- lib/modem.js
I would like to tackle BuildKit support in dockerode. That required some small changes in docker-modem, because the connection needs to be hijacked to create a session.
The first change (preverse `Upgrade` header) should be safe.
I am uncertain about the second change (ending the request in hijack mode). The tests still pass, but could this have other unintended side effects? To open a session over the docker api, this is needed - otherwise the `upgrade` event is never emittet. But we could allow this to be configured some other way as well.
> Small changes for BuildKit support
